version: '3'
services:
  database:
    image: 'postgres:16.2-alpine'
    container_name: 'book_shop_db'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: qwerty
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: account_service_db
    volumes:
      - pgdata:/var/lib/postgresql/data
#    networks:
#      - config-network

volumes:
  pgdata: