spring.datasource.url=jdbc:postgresql://localhost:5432/book_shop
spring.datasource.username=postgres
spring.datasource.password=1

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

app.jwtSecret= lesnik228
app.jwtExpirationMs= 86400000
