# DataBase
spring.datasource.url=jdbc:postgresql://localhost:5432/book_shop
spring.datasource.username=postgres
spring.datasource.password=1

#  Liquibase
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

# JWT
app.jwtSecret= lesnik228
app.jwtExpirationMs= 86400000

# JMS
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kazulina.nast@gmail.com
spring.mail.password=vhhb xnrj tlkt zpgc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true