spring.session.jdbc.initialize-schema=always

dbUrl=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/book_shop}
dbPassword=${SPRING_DATASOURCE_USERNAME:postgres}
dbUsername=${SPRING_DATASOURCE_PASSWORD:1}
