apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
  labels:
    app: book-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
        - name: book-service
          image: lesniklesnik/book-shop-book-service:1.0.2
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: BOOK_SERVICE_DATABASE_HOST
              value: "postgres"
            - name: CONFIG_SERVICE_URL
              value: "http://config-service:8888"
