spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://config-service:8888
  cloud:
    config:
      fail-fast: true

jwt:
  secret: ${JWT_SECRET:lEsNiKlEsNiK20244202kInSeLkInSeL}
  expiration: ${JWT_EXPIRATION:86400}
