spring:
  application:
    name: registry
  config:
    import: optional:configserver:http://config-service:8888
  cloud:
    config:
      fail-fast: true
      username: user
      password: admin

eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: 8761