spring:
  application:
    name: registry
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true

eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: false
    fetch-registry: false