apiVersion: apps/v1
kind: Deployment
metadata:
  name: bill-service
  labels:
    app: bill-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bill-service
  template:
    metadata:
      labels:
        app: bill-service
    spec:
      containers:
        - name: bill-service
          image: lesniklesnik/book-shop-bill-service:1.0.2
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: BILL_SERVICE_DATABASE_HOST
              value: "postgres"
            - name: CONFIG_SERVICE_URL
              value: "http://config-service:8888"
