apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  labels:
    app: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: lesniklesnik/book-shop-account-service:1.0.2
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: ACCOUNT_SERVICE_DATABASE_HOST
              value: "postgres"
            - name: CONFIG_SERVICE_URL
              value: "http://config-service:8888"
